- name: Install and start nginx
  hosts: frontend
  tasks: 
  - name: Isatll nginx
    ansible.builtin.package:
      name: nginx
      state: present
      
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes