- name: variables from inventory 
  hosts: frontend
  tasks:
  - name: printing course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"
      