- name: varaibles from args
  hosts: local
  connection: local
  tasks:
  - name: printing course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"
    