- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.name }}"
    loop:
      - { name: 'nginx', state: 'absent'}
      - { name: 'nginx', state: 'present'}
      - { name: 'nginx', state: 'absent'}
  
