- name: functions
  hosts: local
  connection: local
  # vars:
  #   persons: "Ramesh,suresh,kiran,venky"
  tasks:
  - name: check undefined variables
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"